@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "homepage.html +\nhomepage.js" as homepage
skinparam ParticipantBackgroundColor aquamarine
participant DettagliPreventivo
participant PreventivoDAO


utente -> homepage: click preventivo
skinparam ParticipantBackgroundColor aquamarine
homepage -> DettagliPreventivo: AJAX GET(id)
DettagliPreventivo -> PreventivoDAO: getById(id)
PreventivoDAO --> DettagliPreventivo: preventivo
DettagliPreventivo --> homepage: [preventivo]\nstatus code 200
homepage <- homepage: setPopupDettagliPrev(preventivo)
homepage --> utente: Aggiorna vista
@enduml