@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor aquamarine
participant Homepage
participant PreventivoDAO
skinparam ParticipantBackgroundColor coral
participant "homepage.html" as homepage

utente -> Homepage: GET()
skinparam ParticipantBackgroundColor aquamarine
Homepage -> PreventivoDAO: getAllByImpiegatoId(id)
PreventivoDAO --> Homepage: Preventivi gestiti 
Homepage -> PreventivoDAO: getAllPreventiviNotManaged()
PreventivoDAO --> Homepage: Preventivi da gestire
Homepage -> homepage: ThymeLeaf Engine
homepage -->utente: Pagina HTML
@enduml