@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "homepageImpiegato.html +\nhomepageImpiegato.js" as homepage
skinparam ParticipantBackgroundColor aquamarine
participant GetHomepage
participant PreventivoDAO


utente -> homepage: GET()
skinparam ParticipantBackgroundColor aquamarine
homepage -> GetHomepage: AJAX GET()


GetHomepage -> PreventivoDAO: getAllByImpiegatoId(id)
PreventivoDAO --> GetHomepage: preventiviGestiti
GetHomepage -> PreventivoDAO: getAllPreventiviNotManaged()
PreventivoDAO --> GetHomepage: preventiviDaGestire
GetHomepage -> homepage: [preventiviGestiti, preventiviDaGestire]\nstatus code 200
homepage <- homepage: setPreventiviGestiti(preventiviGestiti)
homepage <- homepage: setPreventiviDaGestire(preventiviDaGestire)
homepage --> utente: Aggiorna vista
@enduml