@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "homepageUtente.html +\nhomepageUtente.js" as homepage
skinparam ParticipantBackgroundColor aquamarine
participant GetHomepage
participant ProdottoDAO
participant PreventivoDAO


utente -> homepage: GET()
skinparam ParticipantBackgroundColor aquamarine
homepage -> GetHomepage: AJAX GET()
GetHomepage -> ProdottoDAO: getAll()
ProdottoDAO --> GetHomepage: prodotti
GetHomepage -> PreventivoDAO: getAllByUserId(id)
PreventivoDAO --> GetHomepage: preventivi
GetHomepage -> homepage: [prodotti, preventivi]\nstatus code 200
homepage <- homepage: setProdotti(prodotti)
homepage <- homepage: setPreventivi(preventivi)
homepage --> utente: Aggiorna vista
@enduml