@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "Pagina generica +\nutils.js" as login

utente -> login: click logout

skinparam ParticipantBackgroundColor aquamarine
login -> Logout: GET()
Logout -> Session: invalidate()
Logout --> login: status code 200
login <- login: SessionStorage.clear()
login <- login: window.location.href = "login"
login --> utente: Aggiorna vista
@enduml