@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "homepageImpiegato.html +\nhomepageImpiegato.js" as homepage
skinparam ParticipantBackgroundColor aquamarine
participant PrezzaPreventivo
participant PreventivoDAO


utente -> homepage: click preventivo
skinparam ParticipantBackgroundColor aquamarine
homepage -> PrezzaPreventivo: AJAX GET(id)
PrezzaPreventivo -> PreventivoDAO: getById(id)
PreventivoDAO --> PrezzaPreventivo: preventivo
PrezzaPreventivo --> homepage: [preventivo]\nstatus code 200
homepage <- homepage: setPopupPrevDaPrezzare(preventivo)
homepage --> utente: Aggiorna vista

utente -> homepage: Inserisce prezzo
homepage <- homepage: [prezzo > 0]
homepage -> ControlloPrezzo: AJAX POST(id, prezzo)
ControlloPrezzo -> PreventivoDAO: pricePreventivoById(id, prezzo)
ControlloPrezzo --> homepage: status code 200
homepage <- homepage: setupPage()
homepage --> utente: Aggiorna vista
@enduml