@startuml
legend left
 <back:#coral>   </back> Client side
 <back:#aquamarine>   </back> Server side
endlegend

actor Utente as utente
skinparam ParticipantBackgroundColor coral
participant "homepageUtente.html +\nhomepageUtente.js" as homepage
skinparam ParticipantBackgroundColor aquamarine
participant ControlloPreventivo
participant ProdottoDAO
participant PreventivoDAO


utente -> homepage: Selezione prodotto
homepage <- homepage: showOpzioni()
utente -> homepage: Selezione opzioni
utente -> homepage: click submit
homepage <- homepage: oneOptionChecked()
skinparam ParticipantBackgroundColor aquamarine
homepage -> ControlloPreventivo: AJAX POST()
ControlloPreventivo -> ProdottoDAO: getByCodice(id)
ProdottoDAO --> ControlloPreventivo: prodotto
ControlloPreventivo -> PreventivoDAO: addPreventivo()
ControlloPreventivo --> homepage: [preventivi]\nstatus code 200
homepage <- homepage: setPreventivi(preventivi)
homepage --> utente: Aggiorna vista
@enduml